language: scala

scala:
  - 2.10.4
  - 2.10.5
  - 2.11.7

jdk:
  - openjdk7
  - oraclejdk8

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/57534ac5b1f36eaa92c6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
